import JSZip from 'jszip'
import type { Project } from '../model/types'
import { lintProject } from './lint'
import { generateProject, type GeneratedFile } from './codegen'
import { loadAssetBlob, saveDeployment, type DeploymentRecord } from '../store/db'

export interface BuildResult {
  status: 'success' | 'warning' | 'error'
  errors: number
  warnings: number
  durationMs: number
  files: number
  message: string
  problems: ReturnType<typeof lintProject>
}

export function runBuild(project: Project): BuildResult {
  const start = performance.now()
  const problems = lintProject(project)
  const errors = problems.filter((p) => p.severity === 'error').length
  const warnings = problems.filter((p) => p.severity === 'warning').length
  const files = generateProject(project).length
  const durationMs = Math.round(performance.now() - start)

  const status = errors > 0 ? 'error' : warnings > 0 ? 'warning' : 'success'
  const message =
    status === 'error'
      ? `Build failed: ${errors} blocking issue${errors === 1 ? '' : 's'}`
      : status === 'warning'
        ? `Build successful with ${warnings} warning${warnings === 1 ? '' : 's'}`
        : 'Build successful — no issues'

  return { status, errors, warnings, durationMs, files, message, problems }
}

export async function exportProjectZip(project: Project): Promise<Blob> {
  const zip = new JSZip()
  const files = generateProject(project)
  for (const f of files) zip.file(f.path, f.content)
  // assets (blobs)
  const assets = await Promise.all(
    Object.values(project.assets).map(async (a) => {
      const blob = await loadAssetBlob(a.id)
      return blob ? { name: `public/assets/${a.name}`, blob } : null
    }),
  )
  for (const a of assets) if (a) zip.file(a.name, a.blob)
  zip.file(
    'README.md',
    `# ${project.name}\nGenerated by SaintWorks — a structured, maintainable project.\n`,
  )
  zip.file('project.json', JSON.stringify(project, null, 2))
  return zip.generateAsync({ type: 'blob' })
}

export interface PublishCheck {
  ok: boolean
  blocking: ReturnType<typeof lintProject>
}

export function validateForPublish(project: Project): PublishCheck {
  const problems = lintProject(project)
  const blocking = problems.filter((p) => p.severity === 'error')
  return { ok: blocking.length === 0, blocking }
}

export interface PublishResult {
  deployment: DeploymentRecord
  build: BuildResult
  files: GeneratedFile[]
}

// Actually publish: validate, build, generate the structured output, and
// persist a deployable artifact to IndexedDB. Returns an error instead of
// claiming success when validation or build fails.
export async function publishProject(
  project: Project,
): Promise<PublishResult | { error: string }> {
  const check = validateForPublish(project)
  if (!check.ok) {
    return {
      error: `${check.blocking.length} blocking issue${check.blocking.length === 1 ? '' : 's'} must be resolved before publishing.`,
    }
  }

  const build = runBuild(project)
  if (build.status === 'error') {
    return { error: build.message }
  }

  const files = generateProject(project)
  const deployment = await saveDeployment({
    projectName: project.name,
    fileCount: files.length,
    errors: build.errors,
    warnings: build.warnings,
    files,
  })

  return { deployment, build, files }
}
